CREATE TABLE IF NOT EXISTS Client (
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(200) NOT NULL CHECK(LENGTH(name) >=3)
);

CREATE TABLE IF NOT EXISTS Planet (
    id VARCHAR(50) UNIQUE NOT NULL CHECK(id REGEXP '^[A-Z]*$'),
    name VARCHAR(500) NOT NULL CHECK(LENGTH(name) >= 1)
);

CREATE TABLE IF NOT EXISTS Ticket (
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    client_id INTEGER NOT NULL,
    from_planet_id VARCHAR(50) NOT NULL,
    to_planet_id VARCHAR(50) NOT NULL,
    FOREIGN KEY (client_id) REFERENCES Client(id) ON DELETE CASCADE,
    FOREIGN KEY (from_planet_id) REFERENCES Planet(id) ON DELETE CASCADE,
    FOREIGN KEY (to_planet_id) REFERENCES Planet(id) ON DELETE CASCADE
);